apiVersion: v1
kind: Service
metadata:
  name: track-classifier-api-service
spec:
  selector:
    app: sfit-discovery
    component: track-classifier-api
    version: 0.0.1
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80